name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
     # Optionally generate compile_commands.json
# https://github.com/marketplace/actions/clang-tidy-review
    - uses: ZedThree/clang-tidy-review@v0.6.0
      id: review
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
      
