name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
    - uses: actions/checkout@v2
    
      # https://github.com/marketplace/actions/cppcheck-action    
    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
        
    - name: publish report    
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main' # your branch name goes here
