name: Run clang-format Linter

on: [push]

jobs:

  Create_report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install clang tidy
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y clang-tidy
        
    - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
      run: |
        clang-tidy --fix  --checks="read*,modern*,hicpp*,performance*" *.cpp > report_code_quality.txt
      
    - uses: actions/upload-artifact@v2
      with:
        name: report_code_quality
        path: /report_code_quality.txt


  Treat_Warning_as_errors:
    runs-on: ubuntu-latest

    steps:
 
    - uses: actions/checkout@v2
    
    - name: Install clang tidy
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y clang-tidy
        
    - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
      run: |
        clang-tidy --fix --warnings-as-errors="*" --checks="read*,modern*,hicpp*,performance*" *.cpp > report_code_quality.txt
        echo $? > $env:CLANG_TIDY
        
