name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
    - uses: actions/checkout@v2
    
    - name: c-linter
      uses: ArtificialAmateur/cpp-linter-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
