name: Testing Code

on: [push]

jobs:

  TESTANDO_O_CODIGO: 
    runs-on: ubuntu-latest
    steps:
    
    # TESTING ADDRESS SANITIZER
      - uses: actions/checkout@v2
      - name: create file
        run: echo ronald >> testee.txt
        
        
        
    # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            git config --global user.email "ronald_hobo@outlook.com.br"
            git config --global user.name "Ronald-batista"
            git add .
            git commit -m "criado no CI"
            git tag -a build
            git push --tags
            git push origin main build

