name: Testing Code

on: [push]

jobs:

  TESTANDO_O_CODIGO: 
    runs-on: ubuntu-latest
    steps:
    
    # TESTING ADDRESS SANITIZER
      - uses: actions/checkout@v2
      #- name: Compiling with Address Sanitizer
        #run: |
          #clang -fsanitize=address -g teste.c -o teste
          #./teste
    
   

    # TESTING CODE QUALITY
      - name: Install clang tidy
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y clang-tidy
        
      - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
        run: |
          clang-tidy --fix --warnings-as-errors="*" --checks="read*,modern*,hicpp*,performance*" *.c



         # CREATING REPORT CODE QUALITY
      - name: Install clang tidy
        if: ${{ failure() }}
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y clang-tidy
        
      - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
        run: |
          clang-tidy --fix  --checks="read*,modern*,hicpp*,performance*" *.c > report_code_quality.txt

      - uses: actions/upload-artifact@v2
        with:
          name: report_code_quality
          path: ./report_code_quality.txt
        
