name: Testing Code

on: [push]

jobs:

  TESTANDO_O_CODIGO: 
    runs-on: ubuntu-latest
    steps:
    
    # TESTING ADDRESS SANITIZER
      - uses: actions/checkout@v2
      - name: create file
        run: echo ronald >> testee.txt
          
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git config --global user.email "ronald_hobo@outlook.com.br"
          git config --global user.name "Ronald-batista"
          git pull origin --tags
          git tag
          git tag -d build-deploy2
          git push origin --tags
          git tag build-deploy2
          git add .
          git commit -m "testing tags"
          git push origin main build-deploy2


