name: Testing Code

on: [push]

jobs:

  Testing_Address_Sanitizer:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compiling with Address Sanitizer
        run: |
          clang -fsanitize=address -g teste.c -o teste
          ./teste
  

  Create_report_code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang tidy
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y clang-tidy
        
    - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
      run: |
        clang-tidy --fix  --checks="read*,modern*,hicpp*,performance*" *.c > report_code_quality.txt
      
    - uses: actions/upload-artifact@v2
      with:
        name: report_code_quality
        path: ./report_code_quality.txt


  Testing_code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang tidy
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y clang-tidy
        
    - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
      run: |
        clang-tidy --fix --warnings-as-errors="*" --checks="read*,modern*,hicpp*,performance*" *.c

        
        
