name: Testing Code

on: [push]

jobs:

  TESTANDO_O_CODIGO: 
    runs-on: ubuntu-latest
    steps:
    
    # TESTING ADDRESS SANITIZER
      - uses: actions/checkout@v2
      - name: create file
        run: echo ronald >> testee.txt
        
   # Sending push to build and deploy
      - name: Sending push to build and deploy  # https://github.com/EndBug/add-and-commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Ronald-batista
          author_email: ronald_hobo@outlook.com.br
          message: 'Sending push to build and deploy - Success code test'
          tag: 'build-deploy'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
