name: Testing Code

on: [push]

jobs:

  TESTANDO_O_CODIGO: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    # TESTING CODE QUALITY
      - name: Install clang tidy
        run: rm boto
        
   # CREATE REPORT CODE QUALITY
      - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
        if: ${{ failure() }}
        run: echo "Ronald"
        
      - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
        if: ${{ failure() }}
        run: echo "COM FAILURE"
        
      - name: running clang tidy # with checks readability, mordenize, hipperformace, performance
        run: echo SEM FAILURE"
    
